// Generated by CoffeeScript 1.3.3

describe("Charbroil Data Attribute", function() {
  beforeEach(function() {
    loadFixtures('data-attribute-list.html');
    this.list = $('.categories').charbroil();
    return this.links = $('.categories a');
  });
  return it("should link based on the data attribute letter", function() {
    var letter, link, _i, _len, _ref, _results;
    _ref = this.links;
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      link = _ref[_i];
      letter = $(link).attr('charbroil-key');
      if (letter) {
        _results.push(expect(link).toHaveClass('charbroil-ctrl-' + letter));
      } else {
        _results.push(void 0);
      }
    }
    return _results;
  });
});
