// Generated by CoffeeScript 1.3.3

describe("Charbroil with multiple modifiers", function() {
  beforeEach(function() {
    loadFixtures('default-list.html');
    this.list = $('.categories').charbroil({
      modifier: ['command', 'shift']
    });
    return this.links = $('.categories a');
  });
  return it("should add shortcut class for command and shift with matching hot key", function() {
    var letter, link, _i, _len, _ref, _results;
    _ref = this.links;
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      link = _ref[_i];
      letter = $(link).find('span').html().charAt(0).toLowerCase();
      expect($(link)).toHaveClass('charbroil-shift-' + letter);
      _results.push(expect($(link)).toHaveClass('charbroil-command-' + letter));
    }
    return _results;
  });
});
